"LR": 0.002
"NUM_ENVS": 1024
"NUM_STEPS": 512
"TOTAL_TIMESTEPS": 2e8
"SAVE_FREQUENCY": 1e7
"FC_DIM_SIZE": 128
"GRU_HIDDEN_DIM": 128
"UPDATE_EPOCHS": 4
"NUM_MINIBATCHES": 4
"GAMMA": 0.99
"GAE_LAMBDA": 0.95
"CLIP_EPS": 0.2
"SCALE_CLIP_EPS": False
"ENT_COEF": 0.0
"VF_COEF": 0.5
"MAX_GRAD_NORM": 0.5
"ACTIVATION": "tanh"
"ENV_NAME": "multiwalker"
"SEED": 42
"NUM_SEEDS": 2
"ENV_KWARGS": {}
"ANNEAL_LR": True

# WandB Params
"PROJECT": "rebuild-mw-mappo"
"WANDB_MODE": "online"
"ENTITY": "" 
"SAVE_PATH": "checkpoints"